# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combo_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_X = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_X.setGeometry(QtCore.QRect(50, 50, 221, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox_X.setFont(font)
        self.comboBox_X.setObjectName("comboBox_X")
        self.comboBox_X.addItem("")
        self.comboBox_X.addItem("")
        self.comboBox_Y = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Y.setGeometry(QtCore.QRect(330, 50, 221, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox_Y.setFont(font)
        self.comboBox_Y.setObjectName("comboBox_Y")
        self.comboBox_Y.addItem("")
        self.comboBox_Y.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 400, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 240, 300, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 60, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # for finding and setting default option for a combo-box
        
        #self.comboBox_X.addItem("Hello")     
        #index = self.comboBox_X.findText("Hello", QtCore.Qt.MatchFixedString)
        #self.comboBox_X.setCurrentIndex(index)

        self.pushButton.clicked.connect(self.pressed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_X.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_X.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_Y.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_Y.setItemText(1, _translate("MainWindow", "1"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.label.setText(_translate("MainWindow", "X xor Y ="))

    def pressed(self):
        x = int(self.comboBox_X.currentText())
        y = int(self.comboBox_Y.currentText())

        if x == y:
            xor = 0
        else:
            xor = 1
        
        self.label.setText("X xor Y =" + " " + str(xor))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
