# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Images.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(20, 20, 611, 291))
        self.photo.setText("")

        self.CURRENT_DIRECTORY = os.path.dirname(os.path.realpath(__file__))
        self.filename = os.path.join(self.CURRENT_DIRECTORY, "assets/duck.jpg")

        self.photo.setPixmap(QtGui.QPixmap(self.filename))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.Duck = QtWidgets.QPushButton(self.centralwidget)
        self.Duck.setGeometry(QtCore.QRect(30, 340, 281, 41))
        self.Duck.setObjectName("Duck")
        self.Cauliflower = QtWidgets.QPushButton(self.centralwidget)
        self.Cauliflower.setGeometry(QtCore.QRect(320, 340, 301, 41))
        self.Cauliflower.setObjectName("Cauliflower")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Duck.clicked.connect(self.show_duck)
        self.Cauliflower.clicked.connect(self.show_cauliflower)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Duck.setText(_translate("MainWindow", "Duck"))
        self.Cauliflower.setText(_translate("MainWindow", "Cauliflower"))

    def show_duck(self):
        self.filename = os.path.join(self.CURRENT_DIRECTORY, "assets/duck.jpg")
        self.photo.setPixmap(QtGui.QPixmap(self.filename))
    def show_cauliflower(self):
        self.filename = os.path.join(self.CURRENT_DIRECTORY, "assets/cauliflower.jpeg")
        self.photo.setPixmap(QtGui.QPixmap(self.filename))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
